[tool.poetry]
name = "top_100"
version = "0.1.2"
description = "Top 100 Visited Sites Web Scraper"
authors = ["reinaldopenno <rapenno@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
beautifulsoup4="4.12.2"
requests="2.31.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
