[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "dynamixel_control"
version = "0.2.4a5"
authors = [
  { name="Kyle", email="dufrenek@oregonstate.edu" },
]
description = "A python package for interfacing with Dynamixel XL-330 motors."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
]
dependencies = [
  "dynamixel-sdk>3.6.0",
  "numpy>1.23.0"
]

[project.urls]
Homepage = "https://github.com/OSUrobotics/dynamixel-control"