[tool.poetry]
name = "mlflowgo"
version = "1.0.1"
description = ""
authors = ["Jimmy Weaver"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
mlflow = "^2.8.1"
scikit-learn = "^1.3.2"
flake8 = "^6.1.0"
shap = "^0.43.0"
pytest = "^7.4.3"
xgboost = "^2.0.2"
lightgbm = "^4.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.pytest.ini_options]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "serial",
]