[package]
name = "yacedar"
version = "0.1.6"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "yacedar"
crate-type = ["cdylib"]

[dependencies]
cedar-policy = "3.0.0"
pyo3 = "0.19.0"
serde_json = "1.0.107"
