[tool.poetry]
name = "corpus-patterns"
description = "Building blocks for spacy Matcher patterns"
version = "0.0.9"
authors = ["Marcelino G. Veloso III <contact@mv3.dev>"]
readme = "README.md"
homepage = "https://mv3.dev"
repository = "https://github.com/justmars/corpus-patterns"
documentation = "https://justmars.github.io/corpus-patterns"
classifiers = [
  "Programming Language :: Python :: 3.11",
  "Typing :: Typed",
  "Development Status :: 4 - Beta",
  "Framework :: Pytest",
]

[tool.poetry.dependencies]
python = "^3.11"
roman = "^4.1"
inflect = "^7.0"
spacy = {extras = ["apple"], version = "^3.7.2"}
rich = "^13.7.0"
sqlite-utils = "^3.36"
environs = "^9.5.0"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.27.1"

[tool.ruff]
line-length = 120
ignore = ["F401", "F403"]
fixable = ["F", "E", "W", "I001"]
select = ["F", "E", "W", "I001"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
