[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "huekit"
version = "0.0.3"
authors = [
  { name="AuraPy", email="zayanarshad@aurapy.co.uk" },
]
description = "Alternative to colorama, has more colors and ANSI features."
readme = "README.md"
requires-python = ">=3.9"

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]