[project]
name = "ispras-crisp"
version = "0.1.7"
description = "Coding Rules at ISP"
dependencies = [
    "ruff~=0.1.0",
    "pycodestyle~=2.11.1",
    "black~=23.9.1",
    "colorama>=0.4.6",
    "GitPython>=3.1.38",
    "deepmerge>=1.1.0",
    "wcmatch>=8.5",
    "tomlkit>=0.12.1",
]
requires-python = ">=3.8"
readme = "README.md"
authors = [
    { name = "Konstantin Arkhipenko", email = "arkhipenko@ispras.ru" },
]

[project.license]
text = "MIT"

[project.scripts]
crisp = "crisp.cli:main"

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[tool.ruff]
extend-exclude = []
line-length = 88
select = [
    "A",
    "ARG",
    "B",
    "C4",
    "COM",
    "D",
    "F",
    "I",
    "INP",
    "ISC",
    "N",
    "NPY",
    "Q",
    "RUF013",
    "UP",
]
ignore = [
    "B028",
    "B905",
    "COM812",
    "D10",
    "D203",
    "D212",
    "D213",
    "D214",
    "D215",
    "D401",
    "D404",
    "D405",
    "D406",
    "D407",
    "D408",
    "D409",
    "D410",
    "D411",
    "D412",
    "D413",
    "D414",
    "D415",
    "D416",
    "D417",
    "N803",
    "N806",
    "N812",
    "UP030",
    "UP032",
]

[tool.crisp]
exclude = []
line-length = 88
default-branch = "main"

[tool.black]
extend-exclude = ""
line-length = 88

[tool.pdm.build]
include = [
    "crisp/",
]

[tool.pdm.dev-dependencies]
dev = [
    "Sphinx>=7.1.2",
    "sphinx-immaterial>=0.11.7",
    "twine>=4.0.2",
]
