[build-system]
requires = [
    "setuptools>=62.0.0",
    "wheel",
]
build-backend = "setuptools.build_meta"

[project]
name = "energy_assistant"
version = "0.0.93"
description = "Energy Assistant"
readme = "Readme.md"
authors = [
    { name = "The Energy Assistant Creators", email = "pail23@users.noreply.github.com" },
]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.11",
]
keywords = [
    "energy assistant",
    "home assistant",
]
dependencies = [
    "SQLAlchemy==2.0.23",
    "requests",
    "fastapi==0.104.1",
    "fastapi-socketio",
    "pydantic-settings==2.0.3",
    "pyyaml >= 6.0.1",
    "alembic==1.12.1",
    "aiosqlite==0.19.0",
    "python-dotenv",
    "uvicorn[standard]==0.23.2",
    "apscheduler==3.10.4",
    "paho-mqtt==1.6.1",
    "jinja2==3.1.2",
    "colorlog==6.7.0",
    "emhass==0.6.0",
    "energy_assistant_frontend==0.0.50",
]
requires-python = ">=3.11"

[project.license]
file = "LICENSE"

[project.optional-dependencies]
dev = [
    "httpx==0.25.1",
    "bumpver",
    "isort",
    "pip-tools",
    "black==23.7.0",
    "codespell==2.2.5",
    "mypy==1.6.1",
    "ruff==0.1.1",
    "pytest==7.4.3",
    "pytest-asyncio==0.21.1",
    "pytest-aiohttp==1.0.4",
    "pytest-cov==4.1.0",
    "pre-commit==3.3.3",
    "types-PyYAML",
    "types-requests",
    "types-paho-mqtt",
    "pandas-stubs",
]

[project.scripts]
eass = "app.main:main"

[project.urls]
Homepage = "https://github.com/pail23/energy-assistant-backend"

[tool.setuptools]
packages = [
    "app",
    "migrations",
]

[tool.isort]
profile = "black"
force_sort_within_sections = true
known_first_party = [
    "tests",
]
forced_separate = [
    "tests",
]
combine_as_imports = true

[tool.ruff]
target-version = "py311"
select = [
    "B007",
    "B014",
    "C",
    "D",
    "E",
    "F",
    "ICN001",
    "PGH004",
    "PLC0414",
    "SIM105",
    "SIM117",
    "SIM118",
    "SIM201",
    "SIM212",
    "SIM300",
    "SIM401",
    "T20",
    "TRY004",
    "RUF006",
    "W",
]
ignore = [
    "D202",
    "D203",
    "D213",
    "D404",
    "D406",
    "D407",
    "D411",
    "E501",
    "E731",
    "T201",
]
exclude = [
    "migrations",
]
line-length = 100

[tool.ruff.per-file-ignores]
"app/models/__init__.py" = [
    "F401",
]

[tool.black]
target-version = [
    "py311",
]
line-length = 100
exclude = "migrations"

[tool.mypy]
python_version = "3.11"

[[tool.mypy.overrides]]
module = [
    "app.*",
]
ignore_missing_imports = true
follow_imports = "skip"
disallow_untyped_defs = true
disallow_untyped_calls = true

[tool.pytest.ini_options]
asyncio_mode = "auto"
pythonpath = [
    ".",
]
testpaths = [
    "tests",
]
norecursedirs = [
    ".git",
]
disable_test_id_escaping_and_forfeit_all_rights_to_community_support = true
markers = [
    "tmp: Temporary",
    "optional: Optional",
]
env = [
    "APP_CONFIG_FILE=test",
]

[flake8-pytest-style]
fixture-parentheses = false

[mccabe]
max-complexity = 25
