[project]
name = "coki"
version = "0.4.2"
authors = [
  { name="Lucas Abbate", email="abbatelucas@gmail.com" },
  { name= "NicolÃ¡s Castro", email="nicolaspcastro@gmail.com"}
]
description = "Coki: un paquete para revisar los precios de Cocos"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: Microsoft :: Windows :: Windows 10",
    "Development Status :: 2 - Pre-Alpha"
]
dependencies = [
    "requests",
    "pandas",
    "numpy",
    "hatchling",
    "tabulate",
    "cryptography"
]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"