[build-system]
requires = ["setuptools >= 61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "model-evaluator"
version = "1.0.13"
authors = [
    { name = "Artyom Galyan", email = "galyanartyom@gmail.com" }
]
description = "Library for beautiful training loop for PyTorch"
requires-python = ">=3.10.0"
dependencies = ['numpy', 'torch', 'scikit-learn', 'matplotlib', 'ipython', 'pandas']
readme = {file = "README.md", content-type = "text/markdown"}

[tool.poetry]
readme = "README.md"