[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = 'spotlighter'
version = '0.0.6'
description = 'auto-preprocess GL to upload spotlight'
readme = "README.md"
authors = [
    {name ="Sgt. Park", email="kinphw@naver.com"},
]

#Except Built-in Module
dependencies = [
    "pandas >= 2.1.2",
    "tqdm >= 4.66.1",
    "numpy >= 1.26.2",
    "pymysql >= 1.1.0",
    "sqlalchemy >= 2.0.23",
    "pyodbc >= 5.0.1",
]

[tool.hatch.build.targets.wheel]
packages = ["spotlight"]