[project]
name = "calculator_mgaidy"
version = "0.0.4"
authors = [
  { name="Mindaugas", email="mindaugas9507@gmail.com" },
]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/pypa/sampleproject"
Issues = "https://github.com/pypa/sampleproject/issues"

[tool.mypy]
plugins = ["mypy_pytest.plugin"]

[tool.flake8]
max-line-length = 88

[tool.pytest]
testpaths = ["tests"]